### ISSUE TITLE
[Bug] Unabel to pip install keplergl

### ISSUE THREAD

**Issue by tourist-C** [keplergl/kepler.gl#1300]
**Describe the bug**
Failed to install keplergl.

**To Reproduce**
1. Start Anaconda Prompt
2. Activate virtual env
3. pip install keplergl

```
Collecting keplergl
  Using cached https://files.pythonhosted.org/packages/2f/a0/ea13a2cc4071fddc91a6ea530d0349e4b943a4a8839209a7facecee37db3/keplergl-0.2.1.tar.gz
Requirement already satisfied: ipywidgets<8,>=7.0.0 in c:\users\curtis\appdata\local\continuum\anaconda3\envs\tf2a\lib\site-packages (from keplergl) (7.5.1)
Collecting traittypes>=0.2.1 (from keplergl)
  Using cached https://files.pythonhosted.org/packages/9c/d1/8d5bd662703cc1764d986f6908a608777305946fa634d34c470cd4a1e729/traittypes-0.2.1-py2.py3-none-any.whl
Collecting geopandas>=0.5.0 (from keplergl)
  Using cached https://files.pythonhosted.org/packages/f7/a4/e66aafbefcbb717813bf3a355c8c4fc3ed04ea1dd7feb2920f2f4f868921/geopandas-0.8.1-py2.py3-none-any.whl
Requirement already satisfied: pandas>=0.23.0 in c:\users\curtis\appdata\local\continuum\anaconda3\envs\tf2a\lib\site-packages (from keplergl) (1.0.1)
Collecting Shapely>=1.6.4.post2 (from keplergl)
  Using cached https://files.pythonhosted.org/packages/0a/e2/1b7aba5ce9804998581efeab455d8a1a902f992f20d2e15dd4ab0a7db4db/Shapely-1.7.1-cp36-cp36m-win_amd64.whl
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\curtis\appdata\local\continuum\anaconda3\envs\tf2a\lib\site-packages (from ipywidgets<8,>=7.0.0->keplergl) (5.3.4)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\curtis\appdata\local\continuum\anaconda3\envs\tf2a\lib\site-packages (from ipywidgets<8,>=7.0.0->keplergl) (4.4.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\curtis\appdata\local\continuum\anaconda3\envs\tf2a\lib\site-packages (from ipywidgets<8,>=7.0.0->keplergl) (3.5.1)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in c:\users\curtis\appdata\local\continuum\anaconda3\envs\tf2a\lib\site-packages (from ipywidgets<8,>=7.0.0->keplergl) (7.16.1)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\curtis\appdata\local\continuum\anaconda3\envs\tf2a\lib\site-packages (from ipywidgets<8,>=7.0.0->keplergl) (4.3.2)
Collecting fiona (from geopandas>=0.5.0->keplergl)
  Using cached https://files.pythonhosted.org/packages/88/62/69347ba2c41b526e1953c4cb66d51170b2869808863c03af202ba0121670/Fiona-1.8.17.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Curtis\AppData\Local\Temp\pip-install-qwrvdd7o\fiona\
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by thenick775** [comment]
I actually just did this and it worked as intended, could you post your environment configuration?

I used pip 20.2.3 with python 3.7

**Comment by rezw4n** [comment]
Hey there! I was able to produce this error on my conda environment. Apparently this is more of a Geopandas installation error. But good news is you can fix it easily! Follow these steps and it should fix your problem:

- First make sure you're in the correct environment in Anaconda. _(Creating a new environment for your project is suggested but it should work in base environment as well)_

- Then open up the command prompt and install Geopandas using ```conda install geopandas``` command.

- After that run ```pip install defusedxml``` and ```python3 -m pip install --upgrade Pillow``` on the same command prompt to make sure all the dependencies work as expected.

- Finally install Kepler.Gl using ```pip install keplergl``` on the same conda environment.

This should fix all the errors. Hope this helps!

**Comment by rodighiero** [comment]
I have a similar error:

`    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lr/mmry4yv506b3rqk3bgm2s_j80000gn/T/pip-install-e644uq2q/shapely_54277eaa53a24e14a74f90bf7ebc8374/setup.py'"'"'; __file__='"'"'/private/var/folders/lr/mmry4yv506b3rqk3bgm2s_j80000gn/T/pip-install-e644uq2q/shapely_54277eaa53a24e14a74f90bf7ebc8374/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/lr/mmry4yv506b3rqk3bgm2s_j80000gn/T/pip-pip-egg-info-9jkwy0m2
         cwd: /private/var/folders/lr/mmry4yv506b3rqk3bgm2s_j80000gn/T/pip-install-e644uq2q/shapely_54277eaa53a24e14a74f90bf7ebc8374/
    Complete output (12 lines):
    Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
    Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
    Failed `CDLL(/usr/local/lib/libgeos_c.dylib)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lr/mmry4yv506b3rqk3bgm2s_j80000gn/T/pip-install-e644uq2q/shapely_54277eaa53a24e14a74f90bf7ebc8374/setup.py", line 85, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/private/var/folders/lr/mmry4yv506b3rqk3bgm2s_j80000gn/T/pip-install-e644uq2q/shapely_54277eaa53a24e14a74f90bf7ebc8374/shapely/_buildcfg.py", line 190, in <module>
        lgeos = load_dll('geos_c', fallbacks=alt_paths)
      File "/private/var/folders/lr/mmry4yv506b3rqk3bgm2s_j80000gn/T/pip-install-e644uq2q/shapely_54277eaa53a24e14a74f90bf7ebc8374/shapely/_buildcfg.py", line 162, in load_dll
        raise OSError(
    OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib']
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by rodighiero** [comment]
Solved: 
brew install geos   
brew install gdal

**Comment by rodighiero** [comment]
I was wrong, I still have problems in running keplergl on OS X.

**Comment by rezw4n** [comment]
> I was wrong, I still have problems in running keplergl on OS X.

Have you tried installing Kepler.GL using a conda environment?

**Comment by rodighiero** [comment]
You are right, Conda saved me. Thank you for the help.
