### ISSUE TITLE
[Bug]Kepler.gl demo became white screen if I click some type layers(Cluster, Grid, Hexbin and 3D) to change the types of Layers.

### ISSUE THREAD

**Issue by Sanuki-073** [keplergl/kepler.gl#1767]
**Describe the bug**
Hello, thanks for this useful software!

When I click "Grid" and "3D"(the other may be mentioned in #1760), "Hexbin"(the other mentioned in it #1766 ), and "Cluster" (new Bug report), the website became a white screen.

There are 2 pattern error logs: "3D"'s error and others error.

"3D"'s error log
bundle.js:8 Uncaught TypeError: Cannot read properties of undefined (reading 'label')
    at a.value (bundle.js:8:195129)
    at bundle.js:20:245607
    at Array.map (<anonymous>)
    at bundle.js:20:245506
    at Xo (bundle.js:524:57931)
    at Ia (bundle.js:524:66792)
    at yu (bundle.js:524:105389)
    at sl (bundle.js:524:96718)
    at ul (bundle.js:524:96643)
    at $u (bundle.js:524:93673)

others' error log is the same.
error log:
Uncaught TypeError: Cannot read properties of undefined (reading 'condition')
    at y.value (bundle.js:14:221309)
    at y.value (bundle.js:14:220672)
    at y.value (bundle.js:14:232370)
    at za (bundle.js:524:69877)
    at Na (bundle.js:524:69672)
    at yu (bundle.js:524:105471)
    at sl (bundle.js:524:96718)
    at ul (bundle.js:524:96643)
    at $u (bundle.js:524:93673)
    at bundle.js:524:45315

**To Reproduce**
1. Go to ['sample data'](https://kepler.gl/demo/earthquakes)
2. Click on "Cluster"(Grid, Hexbin, or 3D)
3. See an error

**Expected behavior**
Change to Cluster (Grid, Hexbin, or 3D) Layer

**Desktop (please complete the following information):**
 - OS:macos
 - Browser chrome
 - Version 100.0.4896.60

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/pull/1795

**Comment by jlondonob** [comment]
While #1795 gets merged, you can bypass this error by downloading the map as an editable HTML file. Work on this file as if it were the demo page. All layer types will work.

**Comment by heshan0131** [comment]
Fix is merged, close for now
