### ISSUE TITLE
cannot use the function of Grid and Hexbin

### ISSUE THREAD

**Issue by jbaijing** [keplergl/kepler.gl#1786]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by WBoode** [comment]
Got the same issue.

Basically, selecting the Grid option gives you a white screen, and the following errors in the console.

"events.mapbox.com/events/v2?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja2tyMjNhcWIwc29sMnVzMThoZ3djNXhzIn0._hfBNwCD7pCU7RAMOq6vUQ:1 
      
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.mapbox.com/events/v2?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja2tyMjNhcWIwc29sMnVzMThoZ3djNXhzIn0._hfBNwCD7pCU7RAMOq6vUQ:1 
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
bundle.js:97 
        
       Image "dot-11" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event.
w @ bundle.js:97
bundle.js:97 
        
       Image "dot-10" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event.
w @ bundle.js:97
bundle.js:524 
        
       TypeError: Cannot read properties of undefined (reading 'condition')
    at y.value (bundle.js:14:221309)
    at y.value (bundle.js:14:220672)
    at y.value (bundle.js:14:232370)
    at za (bundle.js:524:69877)
    at Na (bundle.js:524:69672)
    at yu (bundle.js:524:105471)
    at sl (bundle.js:524:96718)
    at ul (bundle.js:524:96643)
    at $u (bundle.js:524:93673)
    at bundle.js:524:45315
eu @ bundle.js:524
bundle.js:524 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'condition')
    at y.value (bundle.js:14:221309)
    at y.value (bundle.js:14:220672)
    at y.value (bundle.js:14:232370)
    at za (bundle.js:524:69877)
    at Na (bundle.js:524:69672)
    at yu (bundle.js:524:105471)
    at sl (bundle.js:524:96718)
    at ul (bundle.js:524:96643)
    at $u (bundle.js:524:93673)
    at bundle.js:524:45315"

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/pull/1795

**Comment by heshan0131** [comment]
Fix is merged, close now
