### ISSUE TITLE
[Bug] App crashes when applying filters

### ISSUE THREAD

**Issue by amardeep-developper** [keplergl/kepler.gl#2064]
## Issue
When i upload a csv and apply any filter on  integer, float or time type values, my app crashes.

I get error in `Rangeplot` component.

Error:
`message: "process is not defined"
stack: "ReferenceError: process is not defined\n    at isTest (http://localhost:3000/static/js/bundle.js:224063:3)\n
    at RangePlot (http://localhost:3000/static/js/bundle.js:168239:44)\n   `

**To Reproduce**
1. Followed steps mentioned in the [doc](https://docs.kepler.gl/docs/api-reference/get-started) 

I followed steps mentioned in Kepler.gl doc: https://docs.kepler.gl/docs/api-reference/get-started

**Comment by DongMinn** [comment]
i solved this issue by
https://github.com/vfile/vfile/issues/38#issuecomment-640479137

**Comment by albcunha** [comment]
I got the same problem. here are another solutions: 
https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined
