### ISSUE TITLE
[Bug] https://kepler.gl/demo not loading

### ISSUE THREAD

**Issue by vipermax** [keplergl/kepler.gl#2336]
**Describe the bug**
https://kepler.gl/demo is not working and not loading

**To Reproduce**
1. Go to [https://kepler.gl/demo](https://kepler.gl/demo)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Detail**
`bundle.js:533 Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at t.findDOMNode (bundle.js:602:115730)
    at r.__getComponentNode (bundle.js:45:86451)
    at g.componentDidMount (bundle.js:45:88528)
    at lu (bundle.js:533:100795)
    at e (bundle.js:533:100562)
    at cu (bundle.js:533:100569)
    at bundle.js:533:111959
    at fc (bundle.js:533:112470)
    at Qu (bundle.js:533:106220)
    at Do (bundle.js:533:46796)
is @ bundle.js:533
bundle.js:533 Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at t.findDOMNode (bundle.js:602:115730)
    at n.value (bundle.js:75:46026)
    at n.value (bundle.js:75:41702)
    at lu (bundle.js:533:100795)
    at e (bundle.js:533:100562)
    at cu (bundle.js:533:100569)
    at bundle.js:533:111959
    at fc (bundle.js:533:112470)
    at Qu (bundle.js:533:106220)
    at Do (bundle.js:533:46796)
is @ bundle.js:533
bundle.js:533 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at t.findDOMNode (bundle.js:602:115730)
    at r.__getComponentNode (bundle.js:45:86451)
    at g.componentDidMount (bundle.js:45:88528)
    at lu (bundle.js:533:100795)
    at e (bundle.js:533:100562)
    at cu (bundle.js:533:100569)
    at bundle.js:533:111959
    at fc (bundle.js:533:112470)
    at Qu (bundle.js:533:106220)
    at Do (bundle.js:533:46796)`

**Comment by TATA633** [comment]
same

**Comment by ThatDezKnightGuy** [comment]
Adding to this - I see the same error on opening the /demo

OS: MacOS Ventura 13.5.2
Browser: Chrome 116.0.5845.187

And the React Error is noted here: https://legacy.reactjs.org/docs/error-decoder.html/?invariant=188
`Unable to find node on an unmounted component.`

**Comment by rbrown1010** [comment]
same

**Comment by zinone** [comment]
same. is it temporary error?  when it would be available?

**Comment by bmericskay** [comment]
Same...but i hope it's temporary ;)

**Comment by jk053** [comment]
Facing the same error. when it would be available?

**Comment by ThatDezKnightGuy** [comment]
I've just been able to access the demo again. It looks to have been resolved by https://github.com/keplergl/kepler.gl/pull/2338

**Comment by Heimdallgg** [comment]
same error, tried to upload a csv of 400 megabytes. maybe is too big for the software?

**Comment by Heimdallgg** [comment]
whitepage when i tried to upload a csv using a link

**Comment by ejain** [comment]
https://kepler.gl/demo now loads fine for me.
