### ISSUE TITLE
can no longer start the local development webserver

### ISSUE THREAD

**Issue by geoHeil** [keplergl/kepler.gl#529]
On the latest tag (1.0.0) I can no longer start the development webserver:

```
➜  kepler.gl git:(d1b791b) node --version
v10.15.3
➜  kepler.gl git:(d1b791b) npm --version
6.4.1
➜  kepler.gl git:(d1b791b) npm start

> kepler.gl@1.0.0 start /Users/geoheil/development/kepler.gl
> npm run install-and-start -- examples/demo-app start-local


> kepler.gl@1.0.0 install-and-start /Users/geoheil/development/kepler.gl
> node ./scripts/install-and-start "examples/demo-app" "start-local"


> @ start-local /Users/geoheil/development/kepler.gl/examples/demo-app
> webpack-dev-server --mode development --env.es6 --progress --hot --open

webpack-dev-server 2.11.3
webpack 2.7.0
Usage: https://webpack.js.org/configuration/dev-server/

Config options:
  --config  Path to the config file
                        [string] [Standard: webpack.config.js or webpackfile.js]
  --env     Environment passed to the config, when it is a function

Basic options:
  --context    The root directory for resolving entry point and stats
                                      [string] [Standard: The current directory]
  --entry      The entry point                                          [string]
  --watch, -w  Watch the filesystem for changes                        [boolean]
  --debug      Switch loaders to debug mode                            [boolean]
  --devtool    Enable devtool for better debugging experience (Example:
               --devtool eval-cheap-module-source-map)                  [string]
  -d           shortcut for --debug --devtool eval-cheap-module-source-map
               --output-pathinfo                                       [boolean]
  -p           shortcut for --optimize-minimize --define
               process.env.NODE_ENV="production"                       [boolean]
  --progress   Print compilation progress in percentage                [boolean]

Module options:
  --module-bind       Bind an extension to a loader                     [string]
  --module-bind-post                                                    [string]
  --module-bind-pre                                                     [string]

Output options:
  --output-path                 The output path for compilation assets
                                      [string] [Standard: The current directory]
  --output-filename             The output filename of the bundle
                                                  [string] [Standard: [name].js]
  --output-chunk-filename       The output filename for additional chunks
      [string] [Standard: filename with [id] instead of [name] or [id] prefixed]
  --output-source-map-filename  The output filename for the SourceMap   [string]
  --output-public-path          The public path for the assets          [string]
  --output-jsonp-function       The name of the jsonp function used for chunk
                                loading                                 [string]
  --output-pathinfo             Include a comment with the request for every
                                dependency (require, import, etc.)     [boolean]
  --output-library              Expose the exports of the entry point as library
                                                                        [string]
  --output-library-target       The type for exposing the exports of the entry
                                point as library                        [string]

Advanced options:
  --records-input-path       Path to the records file (reading)         [string]
  --records-output-path      Path to the records file (writing)         [string]
  --records-path             Path to the records file                   [string]
  --define                   Define any free var in the bundle          [string]
  --target                   The targeted execution environment         [string]
  --cache                    Enable in memory caching
                     [boolean] [Standard: It's enabled by default when watching]
  --watch-stdin, --stdin     close when stdin ends                     [boolean]
  --watch-aggregate-timeout  Timeout for gathering changes while watching
  --watch-poll               The polling interval for watching (also enable
                             polling)                                  [boolean]
  --hot                      Enables Hot Module Replacement            [boolean]
  --prefetch                 Prefetch this request (Example: --prefetch
                             ./file.js)                                 [string]
  --provide                  Provide these modules as free vars in all modules
                             (Example: --provide jQuery=jquery)         [string]
  --labeled-modules          Enables labeled modules                   [boolean]
  --plugin                   Load this plugin                           [string]
  --bail                     Abort the compilation on first error      [boolean]
  --profile                  Profile the compilation and include information in
                             stats                                     [boolean]
  --hot-only                 Do not refresh page if HMR fails          [boolean]

Resolving options:
  --resolve-alias         Setup a module alias for resolving (Example:
                          jquery-plugin=jquery.plugin)                  [string]
  --resolve-extensions    Setup extensions that should be used to resolve
                          modules (Example: --resolve-extensions .es6 .js)
                                                                         [array]
  --resolve-loader-alias  Setup a loader alias for resolving            [string]

Optimizing options:
  --optimize-max-chunks      Try to keep the chunk count below a limit
  --optimize-min-chunk-size  Try to keep the chunk size above a limit
  --optimize-minimize        Minimize javascript and switches loaders to
                             minimizing                                [boolean]

Stats options:
  --color, --colors   Enables/Disables colors on the console
                                          [boolean] [Standard: (supports-color)]
  --info              Info                            [boolean] [Standard: true]
  --quiet             Quiet                                            [boolean]
  --client-log-level  Log level in the browser (info, warning, error or none)
                                                     [string] [Standard: "info"]

SSL options:
  --https           HTTPS                                              [boolean]
  --key             Path to a SSL key.                                  [string]
  --cert            Path to a SSL certificate.                          [string]
  --cacert          Path to a SSL CA certificate.                       [string]
  --pfx             Path to a SSL pfx file.                             [string]
  --pfx-passphrase  Passphrase for pfx file.                            [string]

Response options:
  --content-base          A directory or URL to serve HTML content from.[string]
  --watch-content-base    Enable live-reloading of the content-base.   [boolean]
  --history-api-fallback  Fallback to /index.html for Single Page Applications.
                                                                       [boolean]
  --compress              Enable gzip compression                      [boolean]

Connection options:
  --port                The port
  --disable-host-check  Will not check the host                        [boolean]
  --socket              Socket to listen
  --public              The public hostname/ip address of the server    [string]
  --host                The hostname/ip address the server will bind to
                                                [string] [Standard: "localhost"]
  --allowed-hosts       A comma-delimited string of hosts that are allowed to
                        access the dev server                           [string]

Optionen:
  --help, -h     Hilfe anzeigen                                        [boolean]
  --version, -v  Version anzeigen                                      [boolean]
  --bonjour      Broadcasts the server via ZeroConf networking on start[boolean]
  --lazy         Lazy                                                  [boolean]
  --inline       Inline mode (set to false to disable including client scripts
                 like livereload)                     [boolean] [Standard: true]
  --open         Open the default browser, or optionally specify a browser name
                                                                        [string]
  --useLocalIp   Open default browser with local IP                    [boolean]
  --open-page    Open default browser with the specified page           [string]

Unbekanntes Argument: mode
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start-local: `webpack-dev-server --mode development --env.es6 --progress --hot --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start-local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/geoheil/.npm/_logs/2019-05-27T07_51_22_381Z-debug.log
child_process.js:656
    throw err;
    ^

Error: Command failed: npm run start-local
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at Object.<anonymous> (/Users/geoheil/development/kepler.gl/scripts/install-and-start.js:31:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kepler.gl@1.0.0 install-and-start: `node ./scripts/install-and-start "examples/demo-app" "start-local"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kepler.gl@1.0.0 install-and-start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/geoheil/.npm/_logs/2019-05-27T07_51_22_405Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kepler.gl@1.0.0 start: `npm run install-and-start -- examples/demo-app start-local`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kepler.gl@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/geoheil/.npm/_logs/2019-05-27T07_51_22_423Z-debug.log
```

**Comment by heshan0131** [comment]
Hi Please `rm -r node_modules && yarn --ignore-engines` in the root dir, then `cd examples/demo-app` run the same command again.

**Comment by geoHeil** [comment]
Strange. No, this doesn't resolve the issue:

```
npm start

> @ start /Users/geoheil/development/kepler.gl/examples/demo-app
> webpack-dev-server --mode development --progress --hot --open

webpack-dev-server 2.11.3
webpack 2.7.0
Usage: https://webpack.js.org/configuration/dev-server/

Config options:
  --config  Path to the config file
                        [string] [Standard: webpack.config.js or webpackfile.js]
  --env     Environment passed to the config, when it is a function

.... 
same stuff as before
....

Unknown Argument: mode
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `webpack-dev-server --mode development --progress --hot --open`
npm ERR! Exit status 1
```

**Comment by heshan0131** [comment]
looking at demo-app/package.json. 
```

**Comment by geoHeil** [comment]
This also did not help. However, I deleted the whole kepler.gl folder and re-cloned. This finally worked.
