### ISSUE TITLE
[Bug]I am trying to load the kepler Gl map in nodejs application. I have installed the prerequisite dependencies too. Now i am getting the error pls help me out to solve the issue.

### ISSUE THREAD

**Issue by syedzubair-dev** [keplergl/kepler.gl#654]
I am trying to load the kepler Gl map in nodejs application. I have installed the prerequisite dependencies too. Now i am getting the error pls help me out to solve the issue.

import KeplerGl from 'kepler.gl';
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\SayedZubair\Documents\KeplerGlApi\server.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keplerglapi@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keplerglapi@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SayedZubair\AppData\Roaming\npm-cache\_logs\2019-08-03T19_34_58_756Z-debug.log

**Comment by heshan0131** [comment]
looks like you didn't have babel setup to parse ES6 syntax

**Comment by heshan0131** [comment]
You might be running an old version of node

**Comment by varunsharma27** [comment]
`import KeplerGl from 'kepler.gl';` seems to be a transpiler issue. To fix this:

1. Add `babel-core`, `babel-loader`, `babel-preset-es2015` to dev-dependencies (`package.json`).
2. Add babel-loader to module.rules of your webpack config (`webpack.config.js`), so the end result looks like this:
```
  module:{
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [ 'babel-loader' ]
        query: { presets: ['es2015'] }
      },
      //...Any other rules
    ]
   }
```
